local config = require("pi-nvim.config")

describe("pi-nvim.config", function()
  it("has correct defaults", function()
    assert.is.equal("pi", config.defaults.pi_cmd)
    assert.is.equal(true, config.defaults.snacks)
    assert.is.equal("<leader>pa", config.defaults.keymaps.ask)
    assert.is.equal("<leader>ps", config.defaults.keymaps.select)
    assert.is.equal("<leader>pf", config.defaults.keymaps.file)
    assert.is.equal("<leader>pp", config.defaults.keymaps.prompt)
  end)

  it("merges user opts with defaults", function()
    local merged = config.merge({ pi_cmd = "/usr/local/bin/pi" })
    assert.is.equal("/usr/local/bin/pi", merged.pi_cmd)
  end)

  it("allows overriding keymaps", function()
    local merged = config.merge({ keymaps = { ask = "<leader>pp" } })
    assert.is.equal("<leader>pp", merged.keymaps.ask)
  end)

  it("handles nil opts gracefully", function()
    local merged = config.merge(nil)
    assert.is.same(config.defaults, merged)
  end)
end)
